development:
  adapter: postgresql
  encoding: unicode
  database: guildcraft_development
  pool: 5
  username: tivtnjmhxpffjp
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: db/guildcraft_test
  pool: 5
  username: tivtnjmhxpffjp
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: db/guildcraft_production
  pool: 5
  username: tivtnjmhxpffjp
  password:
  host: localhost
